sonar.projectKey=HtmlApplication_001
sonar.projectName=HtmlApp
sonar.projectVersion=10
sonar.sources=webapp
sonar.tests=webapp/test
sonar.test.inclusions=webapp/test/unit/**/*.js,webapp/test/integration/**/*.js
sonar.exclusions=webapp/test/**,webapp/localService/**
sonar.javascript.lcov.reportPaths=reports/coverage-lcov/lcov.info
sonar.testExecutionReportPaths=reports/Test-execution.xml