sonar.sources=webapp
Dsonar.inclusions=webapp/** 
sonar.tests=webapp/test
sonar.test.inclusions=webapp/test/**/*.js 
sonar.exclusions=webapp/test/**,webapp/localService/**
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info 
sonar.testExecutionReportPaths=reports/Test-execution.xml